### ISSUE TITLE
Missing CHANGELOG in Hackage

### ISSUE THREAD

**Issue by asr** [meiersi/strict-base-types#10]
I couldn't see the difference between 0.3.0 and 0.4.0 in Hackage.

**Comment by meiersi-11ce** [comment]
What about https://github.com/meiersi/strict-base-types/blob/master/CHANGES?

**Comment by asr** [comment]
The original title of the issue wasn't clear. I renamed it.

Hackage supports a changelog field, so I'm asking for including the CHANGES file in Hackage.

**Comment by meiersi** [comment]
Ok. Thanks for pointing this out.

Andrés Sicard-Ramírez <notifications@github.com> schrieb am Do., 28. Jan.
2016 3:29 PM:

**Comment by asr** [comment]
Thanks!
