### ISSUE TITLE
Maybe doesn't satisfy the monoid properties

### ISSUE THREAD

**Issue by asr** [meiersi/strict-base-types#11]
The `Monoid` instance

```haskell
instance Monoid a => Monoid (Maybe a) where
  mempty = Nothing

  Nothing `mappend` _       = Nothing
  _       `mappend` Nothing = Nothing
  Just x1 `mappend` Just x2 = Just (x1 `mappend` x2)
```
 defined in https://github.com/meiersi/strict-base-types/blob/master/src/Data/Maybe/Strict.hs doesn't satisfy the monoid properties. Is it related to the strictness feature?

**Comment by meiersi** [comment]
Hmm, that wouldn't be good. Could you give a concrete counter-example?

Andrés Sicard-Ramírez <notifications@github.com> schrieb am Do., 28. Jan.
2016 3:32 PM:

**Comment by asr** [comment]
> Could you give a concrete counter-example?

No. But I don't see any problem by fixing the two first equations by

```haskell
Nothing `mappend` m       = m
m       `mappend` Nothing = m
```

**Comment by asr** [comment]
Thanks! (I don't know why I'm not receiving the GitHub notifications via email).
