### ISSUE TITLE
Alternative instance for Maybe

### ISSUE THREAD

**Issue by joe9** [meiersi/strict-base-types#12]
Hello,

Just want to check if an Alternative instance could be added to Maybe.

Thanks

**Comment by meiersi-da** [comment]
Hi @joe9 that won't be possible, as `Alternative` requires a `Functor` instance (via its `Applicative` constraint, see Haddocks [here](http://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Applicative.html#t:Alternative)); and a strict `Maybe` is not a lawful `Functor` as explained [here](https://hackage.haskell.org/package/strict-base-types-0.5.0/docs/Data-Maybe-Strict.html).
